/**
 * Type definitions for the LinkedIn Post Generator project
 * Defines interfaces and types used throughout the application
 */

/**
 * Environment bindings for Cloudflare Workers
 * Contains service bindings that are injected by the Workers runtime
 */
export interface Env {
  /**
   * Workers AI binding for generating content
   * Optional to support fallback mechanisms when AI is unavailable
   */
  AI?: WorkersAI;
}

/**
 * Interface for interacting with Cloudflare Workers AI
 * Provides methods to run AI models with specific parameters
 */
export interface WorkersAI {
  /**
   * Runs an AI model with the provided configuration
   * 
   * @param model - The model identifier (e.g., '@cf/meta/llama-3-8b-instruct')
   * @param options - Configuration options for the model execution
   * @returns Promise containing the AI-generated response
   */
  run: (
    model: string, 
    options: {
      /**
       * Array of message objects in conversation format
       * Typically includes system and user messages
       */
      messages: Array<{
        /**
         * Message role (e.g., 'system', 'user', 'assistant')
         */
        role: string;
        /**
         * Message content
         */
        content: string;
      }>;
      /**
       * Maximum number of tokens to generate in the response
       */
      max_tokens: number;
      /**
       * Controls randomness of output (0.0-1.0)
       * Lower values = more deterministic, higher values = more creative
       */
      temperature?: number;
    }
  ) => Promise<{
    /**
     * The text response generated by the AI model
     */
    response: string;
  }>;
}

/**
 * Available tones for LinkedIn posts
 * Determines the voice and style of the generated content
 */
export type PostTone = 
  | 'professional'  // Formal, authoritative tone
  | 'casual'        // Conversational, approachable tone
  | 'inspirational' // Motivational, uplifting tone
  | 'technical'     // Precise, specialized terminology
  | 'thoughtful'    // Reflective, contemplative tone
  | 'analytical';   // Data-driven, structured analysis tone

/**
 * Available content types for LinkedIn posts
 * Determines the structure and focus of the generated content
 */
export type PostType = 
  | 'thought_leadership'    // Innovative ideas positioning author as an expert
  | 'case_study'            // Real-world examples with results and lessons
  | 'industry_news'         // Updates on sector developments and trends
  | 'personal_achievement'  // Highlighting accomplishments with humility
  | 'industry_insight'      // Analysis of market trends
  | 'career_tip'            // Professional development advice
  | 'company_update';       // Organizational news and milestones

/**
 * Input parameters for LinkedIn post generation
 * Defines the required and optional configuration for content creation
 */
export interface PostParameters {
  /**
   * Main subject of the post (required)
   */
  topic: string;
  
  /**
   * Writing style for the post
   * @default 'professional'
   */
  tone?: PostTone;
  
  /**
   * Whether to add relevant hashtags to the post
   * @default true
   */
  includeHashtags?: boolean;
  
  /**
   * Category of content to create
   * @default 'thought_leadership'
   */
  postType?: PostType;
}

/**
 * Output structure for generated LinkedIn posts
 * Contains both the content and associated metadata
 */
export interface PostOutput {
  /**
   * The formatted post text ready for LinkedIn
   */
  content: string;
  
  /**
   * Additional information about the generated post
   */
  metadata: {
    /**
     * Content classification
     */
    type: string;
    
    /**
     * Main subject of the post
     */
    topic: string;
    
    /**
     * Writing style used
     */
    tone: PostTone;
    
    /**
     * Category of content created
     */
    postType: PostType;
    
    /**
     * Indicates whether AI or template generation was used
     */
    generationMethod: 'ai' | 'template';
    
    /**
     * Total length of the post in characters
     */
    characterCount: number;
    
    /**
     * Suggested optimal posting time for engagement
     */
    recommendedPostTime: string;
    
    /**
     * ISO timestamp of when the post was created
     */
    generatedAt: string;
  };
}